#!/bin/bash
set -e

echo "Setting up K8s Dashboard in OpenSearch..."
echo ""
echo "1. Port-forward OpenSearch Dashboards:"
echo "   kubectl port-forward -n opensearch svc/opensearch-dashboards 5601:5601"
echo ""
echo "2. Open browser: http://localhost:5601"
echo ""
echo "3. Login with: admin / admin"
echo ""
echo "4. Create Index Pattern:"
echo "   - Go to: Management → Index Patterns"
echo "   - Click 'Create index pattern'"
echo "   - Index pattern: fluent-bit*"
echo "   - Time field: @timestamp"
echo "   - Click 'Create'"
echo ""
echo "5. View Logs:"
echo "   - Go to: Discover"
echo "   - Select 'fluent-bit*' index pattern"
echo ""
echo "6. Create Dashboard:"
echo "   - Go to: Dashboard → Create dashboard"
echo "   - Add visualizations for:"
echo "     * Log count over time"
echo "     * Logs by namespace"
echo "     * Logs by pod"
echo "     * Error logs"
echo ""
echo "Starting port-forward now..."
kubectl port-forward -n opensearch svc/opensearch-dashboards 5601:5601
